### ISSUE TITLE
Stop delay option to avoid progress bar flash

### ISSUE THREAD

**Issue by njarraud** [Skyleen77/next-nprogress-bar#46]
In some cases, having the progress bar being displayed up to 100% even if the page loads instantly would be a great option. It currently vanishes after a few ms at the start of the animation which doesn't look great unless you set the `delay` option which removes it all together.

This was available in [nextjs-progressbar](https://www.npmjs.com/package/nextjs-progressbar) as `stopDelayMs `.

```ts
if (!shallow || showOnShallow) {
      if (timer) clearTimeout(timer);
      timer = setTimeout(() => {
        NProgress.done(true);
      }, stopDelayMs);
}
```

**Comment by Skyleen77** [comment]
You now have a `stopDelay` parameter on the last version (2.3.8). Tell me if it's good for you.

**Comment by njarraud** [comment]
There is a bug when using this new `stopDelay` property.
Sometimes, the progress bar flashes once quickly and then reappears again to last for the duration of the `stopDelay`value.
Or even flashes 2 short times with a time interval.

**Comment by Skyleen77** [comment]
Sure enough, I fixed that. I've done a lot of testing and it seems to be good now.
Please upgrade to version 2.3.9 and confirm that it works well.

Thanks

**Comment by njarraud** [comment]
Still the same issues with flashing when the stopDelay param is used.

**Comment by Skyleen77** [comment]
Could you send me a codesandox with the bug ?

**Comment by l0gicgate** [comment]
The issue is with this logic:
https://github.com/Skyleen77/next-nprogress-bar/blob/main/src/PagesProgressBar.tsx#L115

You shouldn't call `NProgress.done()` if `NProgress.start()` was never called due to the `delay` option being set.
